name: Demo
on: 
  push:
    branches:
      - 0.0.3
  pull_request:
    branches:
      - master
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Repository
        uses: actions/checkout@v2
      - 
        name: Setup Python
        uses: actions/setup-python@v2
      -
        name: Find
        run: find . -name "*.py"
      - 
        name: Install Package
        run: |
          pip install flask
          pip install flask[async]
          pip install httpx
          pip install flake8
      - 
        name: Check Flake8
        run: flake8 app.py
        
  pytest:
    needs: flake8
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Repository
        uses: actions/checkout@v2
      - 
        name: Setup Python
        uses: actions/setup-python@v2
      - 
        name: Install Chrome
        run: |
          sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo apt update
          sudo apt-get install google-chrome-stable
      - 
        name: Install Package
        run: |
          pip install chromedriver-binary==93.*
          pip install selenium
          pip install pytest
          pip install flask
          pip install flask[async]
          pip install httpx
      - 
        name: Start App
        run: python app.py &
      - 
        name: Start Test
        run: pytest test.py
      - 
        name: Job Status
        run: echo "This job's status is ${{ job.status }}."
